trigger:
  branches:
    include:
      - uat
      - UAT
  paths:
    include:
      - 'force-app/*' 

pr: none

pool:
  vmImage: ubuntu-latest

variables:
  - group: uat

stages:
  - stage: DeployStage
    jobs: 
      - job: UAT_Deploy
      - template: ../ado_templates/template.yaml
        parameters: 
            SF_INSTANCE_URL: $(SF_INSTANCE_URL)
            SF_ALIAS: $(SF_ALIAS)
            SF_USERNAME: $(SF_USERNAME)
            SF_CLIENT_ID: $(SF_CLIENT_ID)
            SECURE_FILE_NAME: 'server.key'
            PR_MERGED: true
          


    
        