# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: #similar to ON keyword in githubActions [By default PUSH]
  branches:
    include:
      - feature/ci-cd
  paths:
    include:
      - 'force-app/*'

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - 'force-app/*' 

pool:
  vmImage: ubuntu-latest

variables:
  - group: developer
  #Define pipeline variables
  - name: TEST_LEVEL
    value: RunSpecifiedTests

stages:
  - stage: ValidateStage
    jobs: 
      - job: Printing_Variables_Information
        steps:
          - checkout: none
            displayName: Skip checkout(default)
          - script: |
              echo $(SF_INSTANCE_URL)
              echo $(SF_ALIAS)
              echo $(SF_CLIENT_ID)
              echo $(SF_USERNAME)
              echo $(CommonSecureFile)
              echo $(SecureFilePath)
              echo 'ArtifactStagingDirectory : ' $(Build.ArtifactStagingDirectory)
              echo 'Pipeline Workspace : ' $(pipeline.workspace)
              echo 'DefaultSystem Working Deirectory : ' $(System.DefaultWorkingDirectory)
      
      - job: Setup_Salesforce
        steps:
          - checkout: self
            fetchDepth: 0
            displayName: Checkout(Manual)
          - script: |
              npm install @salesforce/cli --global
              sf --version
            displayName: Insatall_Salseforce-cli
          - script: |
              sf plugins install code-analyzer
              sf plugins
            displayName: Install_Salesforce-Code-analyzer
          
          - script: |
              echo 'y' | sf plugins install sfdx-git-delta
            displayName: Install_sfdx-git-delta      

          - task: DownloadSecureFile@1
            name: CommonSecureFile
            inputs:
              secureFile: 'server.key'
            displayName: Download Secure File for Authentication

          - script: |
              #Authenticating to Salesforce using JWT
              sf org login jwt --jwt-key-file $(CommonSecureFile.SecureFilePath) --instance-url $(SF_INSTANCE_URL) --username $(SF_USERNAME) --set-default --client-id $(SF_CLIENT_ID)  --alias $(SF_ALIAS)
            displayName: Authenticate with Salesforce
          
          - script: |
              mkdir -p ApexTestsLocal
              sf apex run test --synchronous --target-org $(SF_ALIAS) --test-level RunSpecifiedTests --tests SimpleMathTest --code-coverage --result-format human --output-dir ./ApexTestsLocal/
            displayName: Running Apex Local Tests

          - script: |
              mkdir -p scanned-reports
              sf code-analyzer run --target "force-app" --view table --output-file ./scanned-reports/code_results.html --rule-selector Recommended  
            displayName: Running Code-Analyzer
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'
            displayName: Publish Build Artifacts
          
          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/scanned-reports'
              artifact: 'SF_CLI_SCANNER'
              publishLocation: 'pipeline'
            displayName: Publish SF-CLI Scanner reports

          - script: |
              mkdir -p delta
              sf sgd source delta --to "HEAD" --from "HEAD~1" --output-dir "./delta" --generate-delta --ignore-whitespace --ignore-file .sgdignore
            displayName: Generate delta for 
            
          - script: |
              ls -R ./delta
              cat ./delta/destructiveChanges/destructiveChanges.xml
              cat ./delta/package/package.xml

          - script: |
              if grep -q "<types>" delta/destructiveChanges.xml
                then
                  echo "*** Validate Pre-destructiveChanges in Salesforce ***"
                  sf project deploy start --target-org $(SF_ALIAS) --pre-destructive-changes delta/destructiveChanges/destructiveChanges.xml --manifest delta/destructiveChanges/package.xml --dry-run --wait 10
                else
                  echo 'No Changes to Validate'
              fi

          - script:
               sf project deploy start --target-org $(SF_ALIAS) --source-dir "force-app" --dry-run --wait 10  
            displayName: Vaidating to Salesforce 
