# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - feature/ci-cd

pool:
  vmImage: ubuntu-latest

variables:
  - group: uat  
  #Define pipeline variables
  - name: TEST_CLASS_NAME
    value: AccountTriggerTest

stages:
  - stage: Validate
    jobs: 
      - job: Printing_Variables_Information
        steps:
          - script: |
              echo $(SF_INSTANCE_URL)
              echo $(SF_CLIENT_ID)
              echo $(SF_USERNAME)
              echo $(SF_ALIAS)
              echo $(CommonSecureFile)
          
      - job: Setup
        steps:
          - checkout: none
            displayName: Skip_checkout(default)
          - script: |
              npm install @salesforce/cli --global
              sf --version
            displayName: Insatall_Salseforce-cli
          - script: |
              sf plugins install code-analyzer
              sf plugins
            displayName: Install_Salesforce-Code-analyzer
          
          - script: |
              echo 'y' | sf plugins install sfdx-git-delta
            displayName: Install_sfdx-git-delta
          
          - task: DownloadSecureFile@1
            name: CommonSecureFile
            inputs:
              secureFile: 'server.key'
            displayName: Download Secure File for Authentication
          
          - script: |
              #Authenticating to Salesforce using JWT
              sf org login --jwt-key-file $(CommonSecureFile.SecureFilePath) --insatnce-url $(SF_INSTANCE_URL) --username $(SF_USERNAME) --set-default --client-id $(SF_CLIENT_ID)  --alias $(SF_ALIAS)
            displayName: Authenticate with Salesforce

          - script: |
              mkdir -p ApexTestsLocal
              sf apex run tests --target-org $(SF_ALIAS) --test-level RunLocalTests --code-coverage --result-foramt human --output-dir ./ApexTestsLocal/
