trigger: none

pr:
  branches:
    include:
      - dev
  paths:
    include:
      - 'force-app/*' 

pool:
  vmImage: ubuntu-latest

variables:
  - group: dev

stages:
  - template: ../ado_templates/template.yaml
    parameters: 
      SF_INSTANCE_URL: $(SF_INSTANCE_URL)
      SF_ALIAS: $(SF_ALIAS)
      SF_USERNAME: $(SF_USERNAME)
      SF_CLIENT_ID: $(SF_CLIENT_ID)
      SECURE_FILE_NAME: 'server.key'
      PR_MERGED: false
          


    
        